#!/usr/bin/env php
<?php

use Webapp\Shell\Helpers\Console;

/**
 * 
 */
class hook_file
{
    public static function hooks()
    {
        return dirname(__DIR__);
    }
}

/**
 * 
 */
class hook_ref
{
    protected $ref;

    public function __construct($ref)
    {
        if (null !== $ref) $this->ref = $ref;
    }

    public function getRef()
    {
        return $this->ref;
    }
}

/**
 * Main hook configure
 */
$baseDir = hook_file::hooks();
require_once $baseDir . '/vendor/autoload.php';

/**
 * Main hook
 */
$ref = new hook_ref($_SERVER['argv'][1]);

Console::print('Running Update Hook');
Console::print('Running Hook in ' . hook_file::hooks() . '/hooks');

//Show Ref
Console::print('Ref: '. $ref->getRef());

print_r($_SERVER);

//print_r(file_get_contents('http://localhost:8000/api/projects/3/tags'));

if ($ref->getRef() == "refs/heads/master") {
    $branch = $ref->getRef();
    Console::print("----> not allowed, $branch is protected branch but allowing to push");
    //exit(1);
}

Console::print('Hook Done');