#!/usr/bin/env php
<?php

use Webapp\Shell\Helpers\Console;
use Webapp\Shell\GitReference;
use Webapp\Shell\Helpers\Permission;
use Webapp\Shell\Helpers\Project;

/**
 * 
 */
class hook_file
{
    public static function hooks()
    {
        return dirname(__DIR__);
    }
}

/**
 * Main hook configure
 */
$baseDir = hook_file::hooks();
require_once $baseDir . '/vendor/autoload.php';
require_once $baseDir . '/config/shell.php';

/**
 * Initialize hook
 */
$_SERVER['argv'][1] = 'refs/heads/master';
$_SERVER['SSH_ORIGINAL_COMMAND'] = "git-receive-pack '~/martin-kukolos/testovaci-projekt.git'";

$ref = new GitReference($_SERVER);
$permission = new Permission();
$project = new Project($ref);

Console::print('Running Hook in ' . hook_file::hooks() . '/hooks');
Console::print('Running Update Hook');
Console::print('Project: ' . $project->get()->data->name);

//Show Ref
Console::print('Ref: '. $ref->getRef());

// Just for log
//print_r($_SERVER);

// check if user is allowed to push to branches
$permission->isAllowedToPush($project);

// Send information when hook is done
Console::print('Hook Done');